[CardNews] 공통 컴포넌트 생성
TripleA-Project/TripleA-FrontEnd pull request #19
Opened 2023-06-12 14:25 UTC by www-r

## Motivation
#16 
## Proposed Changes
- 
-
-
## To Reviewers

2023-06-13 05:00 UTC, Ryan-TheLion requested changes
만드시느라 고생많으셨습니다. 👍  죄송하지만, tsx 파일로 작성해서 타입스크립트로 변경부탁드리며, Card/index.tsx 는 사용하지 않는 파일이라면 로컬에서도 지우고 git commit내역에도 반영될 수 있도록 수정해주시면 감사하겠습니다 ㅠㅠ

2023-06-13 05:15 UTC, www-r commented on src/components/CardNews/Bar.jsx
> +import React from 'react'
아하아하 넵 알겠습니다

2023-06-13 07:41 UTC, Ryan-TheLion requested changes
수정사항 반영후 다시 push해주세요

2023-06-13 09:15 UTC, www-r commented
수정했습니다~

2023-06-13 09:56 UTC, Ryan-TheLion approved these changes
수고하셨습니다 👍

2023-06-13 09:56 UTC, Ryan-TheLion commented on src/components/CardNews/ButtonContainerComponent.tsx
> +      <button>{bookmark?.isBookmark}</button>
이 부분은 이후에 실제 북마크 아이콘과 클릭했을 때 이벤트핸들러도 할당해서 기능이 동작할 수 있도록 수정해주시면 될 것 같고, 석화님 버튼(아이콘 버튼 포함) 반영되면 해당 버튼 컴포넌트를 활용하셔서 수정해주셔도 될 것 같습니다

2023-06-13 09:56 UTC, Ryan-TheLion commented on src/components/CardNews/NewsImage.tsx
>    background-image: url(${({thumbnail})=>thumbnail});
이후에 background-image css 속성 대신에  Next Image 컴포넌트를 활용해서 이미지를 렌더링 하는 것에 대해 고민해보셔서 리팩토링 하시는것도 좋을 것 같습니다.

2023-06-13 09:56 UTC, merged

2023-06-14 08:12 UTC, www-r commented on src/components/CardNews/NewsImage.tsx
>    background-image: url(${({thumbnail})=>thumbnail});
네 알겠습니다!